In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Restaurant 2024 Sales (Month + Categories)

<ul>
    <li>
        Categories:
        <ol>
            <li>Burgers</li>
            <li>Pizzas</li>
            <li>Drinks</li>
            <li>Desserts</li>
            <li>Salads</li>
        </ol>
    </li>
</ul>

In [2]:
kababjees_sales_analysis = np.array([[1, 15326, 17427, 9938, 26390, 15733],
 [2, 23289, 27846, 27807, 12135, 27145],
 [3, 21667, 18174, 12797, 8648, 19246],
 [4, 26066, 28812, 10858, 15274, 21279],
 [5, 9018, 16912, 15988, 18456, 22744],
 [6, 15563, 24473, 23141, 21487, 9582],
 [7, 10101, 17217, 28369, 25636, 20233],
 [8, 18216, 17813, 9832, 28137, 14538],
 [9, 24845, 25586, 25135, 12754, 26219],
 [10, 21183, 29441, 12429, 8347, 18956],
 [11, 25193, 19471, 32409, 9357, 16046],
 [12, 21003, 13570, 10425, 8140, 58986]])

In [6]:
print(f"Shape of this dataset: {kababjees_sales_analysis.shape}")
print(f"Dimensions of this dataset: {kababjees_sales_analysis.ndim}")

Shape of this dataset: (12, 6)
Dimensions of this dataset: 2


In [7]:
# Sample data for 1st 4 months
print(kababjees_sales_analysis[0:5])

[[    1 15326 17427  9938 26390 15733]
 [    2 23289 27846 27807 12135 27145]
 [    3 21667 18174 12797  8648 19246]
 [    4 26066 28812 10858 15274 21279]
 [    5  9018 16912 15988 18456 22744]]


In [11]:
# Sample data for 1st 4 months except month's column
print(kababjees_sales_analysis[:5 , 1:5])

[[15326 17427  9938 26390]
 [23289 27846 27807 12135]
 [21667 18174 12797  8648]
 [26066 28812 10858 15274]
 [ 9018 16912 15988 18456]]


## Revenue Insights

In [15]:
# 1. Total Monthly revenue
monthly_sales = kababjees_sales_analysis[: , 1:]
monthly_revenue = monthly_sales.sum(axis=1)
print(monthly_revenue)
# Average monthly revenue

[ 84814 118222  80532 102289  83118  94246 101556  88536 114539  90356
 102476 112124]


In [16]:
# 2. Revenue growth rate (%)
monthly_growth_rate = (monthly_revenue[1:] - monthly_revenue[:-1])/monthly_revenue[:-1]*100
for i, rate in enumerate(monthly_growth_rate, start=2):
    print(f"Month {i} Growth Rate(%): {rate:.2f}%")

Month 2 Growth Rate(%): 39.39%
Month 3 Growth Rate(%): -31.88%
Month 4 Growth Rate(%): 27.02%
Month 5 Growth Rate(%): -18.74%
Month 6 Growth Rate(%): 13.39%
Month 7 Growth Rate(%): 7.76%
Month 8 Growth Rate(%): -12.82%
Month 9 Growth Rate(%): 29.37%
Month 10 Growth Rate(%): -21.11%
Month 11 Growth Rate(%): 13.41%
Month 12 Growth Rate(%): 9.41%


In [ ]:
# 3. Cumulative revenue