# Array Modification

<p> We can modify numpy array in different ways. </p>

## .insert()

In [1]:
import numpy as np

In [2]:
array_1 = np.array([2, 4, 6, 8, 10])
new_array_1 = np.insert(array_1, 0, 0, axis=0)
print(f"Old Array: {array_1}")
print(f"New Array: {new_array_1}")

Old Array: [ 2  4  6  8 10]
New Array: [ 0  2  4  6  8 10]


In [3]:
array_2 = np.arange(1, 100, 5).reshape(4, 5)
new_array_2 = np.insert(array_2, 1, [2, 4, 8, 9, 15], axis=0)
print(f"Old Array:\n {array_2}")
print(f"New Array:\n {new_array_2}")

Old Array:
 [[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]
New Array:
 [[ 1  6 11 16 21]
 [ 2  4  8  9 15]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]


In [4]:
array_3 = np.arange(1, 100, 5).reshape(4, 5)
new_array_3 = np.insert(array_3, 1, [2, 4, 8, 9], axis=1)
print(f"Old Array:\n {array_3}")
print(f"New Array:\n {new_array_3}")

Old Array:
 [[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]
New Array:
 [[ 1  2  6 11 16 21]
 [26  4 31 36 41 46]
 [51  8 56 61 66 71]
 [76  9 81 86 91 96]]


## .append()

In [8]:
array_4 = np.arange(0, 50, 2).reshape(5, 5)
# new_list = np.array([[15, 25, 35, 45, 55]])
new_array_4 = np.append(array_4, np.array([[15, 25, 35, 45, 55]]), axis=0)
print(new_array_4)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [15 25 35 45 55]]


In [9]:
array_5 = np.array([1, 2, 3, 4, 5])
new_array_5 = np.append(array_5, 6)
print(new_array_5)

[1 2 3 4 5 6]


In [10]:
array_6 = np.arange(0, 50, 2).reshape(5, 5)
# new_list = np.array([[15, 25, 35, 45, 55]])
new_array_6 = np.append(array_6, np.array([[15], [25], [35], [45], [55]]), axis=1)
print(new_array_6)

[[ 0  2  4  6  8 15]
 [10 12 14 16 18 25]
 [20 22 24 26 28 35]
 [30 32 34 36 38 45]
 [40 42 44 46 48 55]]


## .concatenate()

In [15]:
array_7a = np.array([1, 2, 3])
array_7b = np.array([4, 5, 6])
print(np.concatenate((array_7a, array_7b), axis=0))

[1 2 3 4 5 6]


## .delete()

In [16]:
array_8 = np.arange(0, 50, 5)
new_array_8 = np.delete(array_8, 5)
print(f"Old Array: \n{array_8}\nNew Array: \n{new_array_8}")

Old Array: 
[ 0  5 10 15 20 25 30 35 40 45]
New Array: 
[ 0  5 10 15 20 30 35 40 45]


In [17]:
array_9 = np.arange(0, 100, 5).reshape(5,4)
new_array_9 = np.delete(array_9, 2, axis=1)
print(f"Old Array: \n{array_9}\nNew Array: \n{new_array_9}")

Old Array: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]
New Array: 
[[ 0  5 15]
 [20 25 35]
 [40 45 55]
 [60 65 75]
 [80 85 95]]


In [18]:
array_10 = np.arange(0, 100, 5).reshape(5,4)
new_array_10 = np.delete(array_10, 2, axis=0)
print(f"Old Array: \n{array_10}\nNew Array: \n{new_array_10}")

Old Array: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]
New Array: 
[[ 0  5 10 15]
 [20 25 30 35]
 [60 65 70 75]
 [80 85 90 95]]
