In [1]:
print("Hello world")

Hello world


# Creating NumPy Arrays

<p>There are different ways to create numpy arrays</p> 

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5]) #1 Dimensional_Array
print(arr1)
print("Type of aarr1: ", type(arr1))
#print("Dimention of arr1: ", np.ndim(arr1) 

[1 2 3 4 5]
Type of aarr1:  <class 'numpy.ndarray'>


In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
arr3 = np.zeros((2, 3)) #2 ---> Rows, 3 ---> Columns
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr4 = np.ones((3, 5))
print(arr4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
arr5 = np.identity(5) # 5 ---> Rows and Columns
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
arr6 = np.arange(11) # will create an array
print(arr6)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
arr7 = np.arange(1, 20) # 1 ---> Startin range, 11 ---> Ending range (exclusive) means n-1
print(arr7)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
arr8 = np.arange(1, 20, 2) 
""" 1 ---> Startin range, 
    11 ---> Ending range (exclusive) means n-1,
    2 ---> Steps
"""
print(arr8)

[ 1  3  5  7  9 11 13 15 17 19]


In [11]:
arr9 = np.linspace(1, 10, 5) # Will generate 5 evenly spaced number between 1 and 10 (inclusive) 
print(arr9)

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:
arr10 = np.linspace(1, 10, 5, endpoint = False) # Will generate 5 evenly spaced number between 1 and 10 (exclusive of 10) 
print(arr10)

[1.  2.8 4.6 6.4 8.2]


In [13]:
arr11 = arr10.copy() # will create a copy of arr10
print(arr11)

[1.  2.8 4.6 6.4 8.2]


In [14]:
arr12 = np.full((3, 3), 3)
print(arr12)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [20]:
arr13 = np.eye(7, 6)
print(arr13)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]
