# NumPy Array Operations

In [1]:
import numpy as np

#### Basic Operations

In [2]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([6, 7, 8, 9, 10])

print(f"Addition: {array_1 + array_2}")
print(f"Addition: {array_1 + 5}")
print(f"Subtraction: {array_1 - array_2}")
print(f"Subtraction: {array_2 - 2}")
print(f"/vector Multiplication: {array_1 * array_2}")
print(f"Scalar multiplication of an array: {array_1*2}")

Addition: [ 7  9 11 13 15]
Addition: [ 6  7  8  9 10]
Subtraction: [-5 -5 -5 -5 -5]
Subtraction: [4 5 6 7 8]
/vector Multiplication: [ 6 14 24 36 50]
Scalar multiplication of an array: [ 2  4  6  8 10]


#### Comparision Operators

In [3]:
print(f"Array 1: {array_1} \nArray 2: {array_2}")

print(array_1 > array_2)
print(array_1 < array_2)
print(array_1 >= array_2)
print(array_1 <= array_2)
print(array_1 == array_2)
print(array_1 != array_2)
print(array_1 > 3)

Array 1: [1 2 3 4 5] 
Array 2: [ 6  7  8  9 10]
[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]
[False False False  True  True]


#### Dot Product

In [4]:
array_3 = np.arange(12).reshape(3, 4)
array_4 = np.arange(1, 13).reshape(4, 3)
print(f"Array 3 is:\n {array_3} \n\nArray 4 is:\n {array_4}")
print(f"\nDot product of array 3 and array4 is:\n {array_3.dot(array_4)}")

Array 3 is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Array 4 is:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Dot product of array 3 and array4 is:
 [[ 48  54  60]
 [136 158 180]
 [224 262 300]]


In [5]:
print(f"Dot product of array 1 and array 2 is: {array_1.dot(array_2)}")

Dot product of array 1 and array 2 is: 130


#### Unary Operation

In [6]:
print(f"Maximum element of this array is: {array_3.max()}")
print(f"Minimum element of this array is: {array_4.min()}")

Maximum element of this array is: 11
Minimum element of this array is: 1


In [7]:
print(f"Maximum elements of every columns are: {array_3.max(axis=0)}")
print(f"Minimum elements of every rows are: {array_3.min(axis=1)}")

Maximum elements of every columns are: [ 8  9 10 11]
Minimum elements of every rows are: [0 4 8]


In [8]:
print(f"Sum of array 4 is: {array_4.sum()}")
print(f"Sum of every column of array 4 is: {array_4.sum(axis=0)}")
print(f"Sum of every row of array 4 is: {array_4.sum(axis=1)}")

Sum of array 4 is: 78
Sum of every column of array 4 is: [22 26 30]
Sum of every row of array 4 is: [ 6 15 24 33]


In [9]:
print(f"Mean of array 1 is: {array_1.mean()}")
print(f"Mean of array 2 is: {array_2.mean()}")
print(f"Mean of every column of array 3 is: {array_3.mean(axis=0)}")
print(f"Mean of every row of array 4 is: {array_4.mean(axis=1)}")

Mean of array 1 is: 3.0
Mean of array 2 is: 8.0
Mean of every column of array 3 is: [4. 5. 6. 7.]
Mean of every row of array 4 is: [ 2.  5.  8. 11.]


In [10]:
print(f"Standard Daviation of array 1 is: {array_1.std()}")
print(f"Standard Daviation of array 1 is: {array_2.std()}")
print(f"Standard Daviation of every column of array 3 is: {array_3.std(axis=0)}")
print(f"Standard Daviation of every row of array 4 is: {array_4.std(axis=1)}")

Standard Daviation of array 1 is: 1.4142135623730951
Standard Daviation of array 1 is: 1.4142135623730951
Standard Daviation of every column of array 3 is: [3.26598632 3.26598632 3.26598632 3.26598632]
Standard Daviation of every row of array 4 is: [0.81649658 0.81649658 0.81649658 0.81649658]


#### Universal Functions

In [11]:
print(f"Median of array 1 is: {np.median(array_1)}")
print(f"Median of array 2 is: {np.median(array_2)}")
print(f"Median of every column of array 3 is: {np.median(array_3, axis=0)}")
print(f"Median of every row of array 4 is: {np.median(array_4, axis=1)}")

Median of array 1 is: 3.0
Median of array 2 is: 8.0
Median of every column of array 3 is: [4. 5. 6. 7.]
Median of every row of array 4 is: [ 2.  5.  8. 11.]


In [12]:
print(f"Sin of array 1: {np.sin(array_1)}")
print(f"Sin of array 3: {np.sin(array_3)}")

Sin of array 1: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Sin of array 3: [[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


In [13]:
print(f"Exponential of array 2: {np.exp(array_2)}")
print(f"Exponential of array 4: {np.exp(array_4)}")

Exponential of array 2: [  403.42879349  1096.63315843  2980.95798704  8103.08392758
 22026.46579481]
Exponential of array 4: [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]


In [14]:
print(f"Square root of array 1 is: {np.sqrt(array_1)}")
print(f"Square root of array 3 is: {np.sqrt(array_3)}")

Square root of array 1 is: [1.         1.41421356 1.73205081 2.         2.23606798]
Square root of array 3 is: [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
