# NumPy Properties & Attributes

In [1]:
import numpy as np

### Shape ---> .shape

<p>Shape describe the number of elements along with dimensions of the array.</p> 

In [2]:
arr1 = np.array([1, 2, 5])
print(arr1)
print("Shape of array 1: ", arr1.shape) #(3, ) ---> indicates a one-dimensional array with 3 elements.

[1 2 5]
Shape of array 1:  (3,)


In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print("Shape of array 2: ", arr2.shape) #(2, 3) ---> indicates a 2-dimensional array with 2 rows and 3 columns.

[[1 2 3]
 [4 5 6]]
Shape of array 2:  (2, 3)


In [4]:
arr3 = np.array([[[1, 2],[3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr3)
print(f"Shape of array 3: {arr3.shape}") #(2, 3, 2) ---> indicates a three-dimensional array with 2 "layers," each containing a 3x2 matrix.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape of array 3: (2, 3, 2)


In [5]:
arr4 = np.array([[[1, 2],[3, 4], [5, 6], [0, 1]], [[7, 8], [9, 10], [11, 12], [1, 0]]])
print(arr4)
print(f"Shape of array 4: {arr4.shape}") #(2, 4, 2) ---> indicates a three-dimensional array with 2 "layers," each containing a 4x2 matrix.

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 0  1]]

 [[ 7  8]
  [ 9 10]
  [11 12]
  [ 1  0]]]
Shape of array 4: (2, 4, 2)


In [6]:
arr5 = np.array([[[[1, 2], [3, 4]], [[4, 6], [7, 8]], [[9, 10], [11, 12]]]])
print(arr5)
print(f"Shape of array 5: {arr5.shape}")

'''
    (1, 3, 2, 2) ---> indicates a four-dimensional array with 1 block, 
    that block containing 3 layers, and each layer being a 2×2 matrix.
'''

[[[[ 1  2]
   [ 3  4]]

  [[ 4  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]]
Shape of array 5: (1, 3, 2, 2)


'\n    (1, 3, 2, 2) ---> indicates a four-dimensional array with 1 block, \n    that block containing 3 layers, and each layer being a 2×2 matrix.\n'

# Dimension ---> .ndim

<p>To check the dimensions, we use <strong>ndim</strong> attribute</p> 

In [7]:
array = np.array(1)
print(f"The dimension of this array is: {array.ndim}")

The dimension of this array is: 0


In [8]:
print(f"The dimension of array 1 is: {arr1.ndim}")

The dimension of array 1 is: 1


In [9]:
print(f"The dimension of array 2 is: {arr2.ndim}")

The dimension of array 2 is: 2


In [10]:
print(f"The dimension of array 3 is: {arr3.ndim}")

The dimension of array 3 is: 3


In [11]:
print(f"The dimension of array 4 is: {arr4.ndim}")

The dimension of array 4 is: 3


In [12]:
print(f"The dimension of array 5 is: {arr5.ndim}")

The dimension of array 5 is: 4


<h1>Size ---> .size</h1>

<p>Size will show the number of to number of elements in the array<p>

In [13]:
print(f"Size of the array is: {array.size}")

Size of the array is: 1


In [14]:
print(f"Size of array 1 is: {arr1.size}")

Size of array 1 is: 3


In [15]:
print(f"Size of array 2 is: {arr2.size}")

Size of array 2 is: 6


In [16]:
print(f"Size of array 3 is: {arr3.size}")

Size of array 3 is: 12


In [17]:
print(f"Size of array 4 is: {arr4.size}")
print(f"Size of array 5 is: {arr5.size}")

Size of array 4 is: 16
Size of array 5 is: 12


# .itemsize and .dtype

<ol> 
    <li>dtype tells you the data type of elements (e.g., int32, float64).</li>
    <li>itemsize tells you the memory size in bytes of each element of that dtype.
    <ul>
        <li>NumPy defaults to 64-bit precision for both integers and floats
        <li>Default int → int64 → 8 bytes </li>
        <li>Default float → float64 → 8 bytes</li>
        </li>
    </ul>  </li>
</ol>

In [25]:
np_array = np.array(5)
print(np_array)
print(f"\nSize of this array is: {np_array.itemsize}")
print(f"The data type of this array is: {np_array.dtype}")

5

Size of this array is: 8
The data type of this array is: int64


In [26]:
np_arr_1 = np.array([1, 2, 3])
print(np_arr_1)
print(f"\nSize of this array is: {np_arr_1.itemsize}")
print(f"The data type of this array is: {np_arr_1.dtype}")

[1 2 3]

Size of this array is: 8
The data type of this array is: int64


In [29]:
np_arr_2a = np.zeros((3, 2), dtype=np.int32)
print(np_arr_2a)
print(f"\nSize of this array is: {np_arr_2a.itemsize}")
print(f"The data type of this array is: {np_arr_2a.dtype}")

[[0 0]
 [0 0]
 [0 0]]

Size of this array is: 4
The data type of this array is: int32


In [28]:
np_arr_2b = np.zeros((3, 2))
print(np_arr_2b)
print(f"\nSize of this array is: {np_arr_2b.itemsize}")
print(f"The data type of this array is: {np_arr_2b.dtype}")

[[0. 0.]
 [0. 0.]
 [0. 0.]]

Size of this array is: 8
The data type of this array is: float64


In [30]:
np_arr_3 = np.linspace(3, 15, 10)
print(np_arr_3)
print(f"\nSize of this array is: {np_arr_3.itemsize}")
print(f"The data type of this array is: {np_arr_3.dtype}")

[ 3.          4.33333333  5.66666667  7.          8.33333333  9.66666667
 11.         12.33333333 13.66666667 15.        ]

Size of this array is: 8
The data type of this array is: float64


In [31]:
np_arr_4a = np.array([2, 6, 8], dtype=np.int32)
print(np_arr_4a)
print(f"\nSize of this array is: {np_arr_4a.itemsize}")
print(f"The data type of this array is: {np_arr_4a.dtype}")

[2 6 8]

Size of this array is: 4
The data type of this array is: int32


In [32]:
np_arr_4b = np.array([2, 6, 8])
print(np_arr_4b)
print(f"\nSize of this array is: {np_arr_4b.itemsize}")
print(f"The data type of this array is: {np_arr_4b.dtype}")

[2 6 8]

Size of this array is: 8
The data type of this array is: int64


# .astype()

<p>In NumPy, .astype() is used to convert (cast) an array to a different dtype.</p>
<ul>
    <li>.astype() does not change the original array; it creates a new one with the specified dtype.</li>
    <li>If you don’t assign the result of .astype() to a new variable, the converted array will still be created but you’ll lose access to it,</li>
</ul>

In [33]:
arr6 = np.array([1, 2, 3], dtype=np.int32)
print(arr6.dtype, arr6.itemsize)   # int32, 4

# Convert to float64
arr_float = arr6.astype(np.float64)
print(arr_float.dtype, arr_float.itemsize)  # float64, 8

int32 4
float64 8


In [35]:
arr7 = np.array([1, 2, 3], dtype=np.int32)
arr7.astype(np.float64)   # conversion happens, but result not stored
print(arr7.dtype)   # still int32

int32


In [45]:
arr8 = np.array([[1, 2, 3],[4, 5, 6]])
print(f"{arr8}\ndata type of this array is: {arr8.dtype} \n")

arr9 = arr8.astype('float')
print(f"{arr9}\nafter conversion: {arr9.dtype}")

[[1 2 3]
 [4 5 6]]
data type of this array is: int64 

[[1. 2. 3.]
 [4. 5. 6.]]
after conversion: float64
