# Reshaping NumPy Array

In [1]:
import numpy as np

In [2]:
array_1 = np.array([[1, 2, 3],[4, 5, 6]])
array_1

array([[1, 2, 3],
       [4, 5, 6]])

## ravel()

<p>This function flatten the multi-dimensional array without lossing original information</p>

In [6]:
print(f"Array 1 from 2D to 1D: {array_1.ravel()}")

Array 1 from 2D to 1D: [1 2 3 4 5 6]


## flatten()

In [3]:
print(f"Array 1 from 2D to 1D: {array_1.flatten()}")

Array 1 from 2D to 1D: [1 2 3 4 5 6]


### reshap()

<p>.reshape() is a function that allows you to change the shape (dimensions) of an array without altering its underlying data.</p>

In [8]:
print(f"Array 1 before reshape: {array_1} \n\nArray 1 after reshape: {array_1.reshape(3, 2)}")

Array 1 before reshape: [[1 2 3]
 [4 5 6]] 

Array 1 after reshape: [[1 2]
 [3 4]
 [5 6]]


### .transpose()

<p>.transpose() function reorders the axis of an array</p>

In [10]:
array_2 = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(f"Transpose of Array 2 is: \n{array_2.transpose()}")

Transpose of Array 2 is: 
[[ 7 10 13]
 [ 8 11 14]
 [ 9 12 15]]


### .stack()

<p>This function is used to join multiple arrays along a new axis.</p>

In [13]:
array_3 = np.arange(1, 11).reshape(2, 5)
array_4 = np.arange(11, 21).reshape(2, 5)
print(np.stack((array_3, array_4)))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [14]:
print(np.hstack((array_3, array_4)))

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [15]:
print(np.vstack((array_3, array_4)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### .split()

<p>In NumPy, splitting an array refers to the process of dividing a single array into multiple smaller sub-arrays.</p>

In [17]:
print(np.split(array_3, 2))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]


In [28]:
print(np.vsplit(array_3, 2))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]


In [31]:
print(np.hsplit(array_3, 5))

[array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]]), array([[ 5],
       [10]])]
